[package]
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]
name = "intercept-fs"
version = "0.1.0"

[dependencies]
lazy_static = "0.2.8"
libc = "0.2.22"

[lib]
crate-type = ["dylib"]
name = "intercept_fs"
